### ISSUE TITLE
Issues in Application DisplayVersion Table column

### ISSUE THREAD

**Issue by naval-sharma** [AsBuiltReport/AsBuiltReport.Microsoft.Windows#25] opened 2024-03-21 09:17 UTC
### Bug description

Hello,
While most of your code runs flawless and to the point, I recently realised that few of the Application DisplayVersion tab, For some odd reason, dont catch (write) . (dot) between digits..and this is random for some applications while others works fine. I have verified the Uninstall RegKey value of the same application and there are dots between digits.

What could be the possible reason here?

### Command-line input

New-AsBuiltReport 

### Steps to reproduce

Default commandline switch

### Expected behaviour

Dots between digits should be written in the report file

### Operating System

Windows 2012/16/19/22

### PowerShell Version

5

### PowerShell Modules

Microsoft.Windows

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/support/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Windows/issues) before submitting this bug report.

**Comment by rebelinux** [comment] 2024-03-21 11:49
Can you show me an example?

**Comment by naval-sharma** [comment] 2024-03-21 12:07
> Can you show me an example? 

Unable to upload sample from mobile, but you can refer to the sample report from the article page itself. Notice the table column "Microsoft Edge Update"  against "Microsoft Edge"  app version or any other application version.

**Comment by rebelinux** [comment] 2024-03-21 13:18
The problem is that I use the Version property but it should be the DisplayVersion. Thanks for reporting the issue

Code with Version property:
```powershell
PS C:\Users\jocolon> $AddRemove | Select-Object -Property DisplayName,Version

DisplayName                                                             Version       
-----------                                                             -------       
7-Zip 19.00 (x64)

DiskMax 6.21
Git

Microsoft Visual C++ 2022 X64 Additional Runtime - 14.36.32532          237272852     
VMware Tools                                                            201523205     
Veeam Backup VSS Integration                                            201392128     
Microsoft ODBC Driver 17 for SQL Server                                 285868037
Microsoft System CLR Types for SQL Server 2019                          251660240     
Lingering Object Liquidator v2                                          16777216
MEM Patching Optimizer                                                  16908295
Microsoft Analysis Services OLE DB Provider                             268440599
Microsoft Visual Studio Tools for Applications 2019 x64 Hosting Support 268466566
Veeam Agent for Microsoft Windows                                       100728832
Microsoft System CLR Types for SQL Server 2012 (x64)                    184818521
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.36.32532             237272852
Veeam VSS Hardware Provider                                             100728832
Local Administrator Password Solution                                   100794368
Microsoft OLE DB Driver for SQL Server                                  302383111
Microsoft Command Line Utilities 15 for SQL Server                      251660240

Google Chrome                                                           122.0.6261.129
Microsoft Edge Update                                                   1.3.185.21
Microsoft Help Viewer 2.3
Npcap
Veeam Installer Service                                                 11

Visual Studio 2017 Isolated Shell for SSMS                              251686548
Microsoft SQL Server Management Studio - 19.3
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.36.32532
SQL Server Management Studio                                            318963716
Microsoft Edge                                                          2030045413
Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32532             237272852
Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664              201367256
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532
Microsoft Analysis Services OLE DB Provider                             268440599
Microsoft Help Viewer 2.3                                               33779347
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664
Veeam Backup Transport                                                  201392128
Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32532          237272852
Microsoft Report Viewer 2012 Runtime                                    184618364
Integration Services                                                    268440851
Microsoft Active Directory Topology Diagrammer                          33689650
Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664           201367256
SSMS Post Install Tasks                                                 318963716
Microsoft Visual Studio Tools for Applications 2019 x86 Hosting Support 268466566
SQL Server Management Studio Language Pack - English                    318963716
Microsoft Visual Studio Tools for Applications 2019
AD Replication Status Tool 1.0                                          51773855
RVTools                                                                 67305473
Administrative Templates (.admx) for Windows 10 October 2020 Update     16777216


PS C:\Users\jocolon> 
```

Code with DisplayVersion property:
```powershell
PS C:\Users\jocolon> $AddRemove | Select-Object -Property DisplayName,DisplayVersion

DisplayName                                                             DisplayVersion 
-----------                                                             -------------- 
7-Zip 19.00 (x64)                                                       19.00

DiskMax 6.21                                                            6.21
Git                                                                     2.43.0

Microsoft Visual C++ 2022 X64 Additional Runtime - 14.36.32532          14.36.32532
VMware Tools                                                            12.3.5.22544099
Veeam Backup VSS Integration                                            12.1.0.2131
Microsoft ODBC Driver 17 for SQL Server                                 17.10.5.1
Microsoft System CLR Types for SQL Server 2019                          15.0.2000.5
Lingering Object Liquidator v2                                          1.0.0
MEM Patching Optimizer                                                  1.2.7.0
Microsoft Analysis Services OLE DB Provider                             16.0.5143.0
Microsoft Visual Studio Tools for Applications 2019 x64 Hosting Support 16.0.31110
Veeam Agent for Microsoft Windows                                       6.1.0.349
Microsoft System CLR Types for SQL Server 2012 (x64)                    11.4.7001.0
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.36.32532             14.36.32532
Veeam VSS Hardware Provider                                             6.1.0.349
Local Administrator Password Solution                                   6.2.0.0
Microsoft OLE DB Driver for SQL Server                                  18.6.7.0
Microsoft Command Line Utilities 15 for SQL Server                      15.0.2000.5

Google Chrome                                                           122.0.6261.129
Microsoft Edge Update                                                   1.3.185.21
Microsoft Help Viewer 2.3                                               2.3.28307
Npcap                                                                   1.60
Veeam Installer Service                                                 11.0.1.1261

Visual Studio 2017 Isolated Shell for SSMS                              15.0.28308.421
Microsoft SQL Server Management Studio - 19.3                           19.3.4.0
Microsoft Visual C++ 2015-2022 Redistributable (x86) - 14.36.32532      14.36.32532.0
SQL Server Management Studio                                            19.3.4.0
Microsoft Edge                                                          122.0.2365.92
Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32532             14.36.32532
Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664              12.0.40664
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532      14.36.32532.0
Microsoft Analysis Services OLE DB Provider                             16.0.5143.0
Microsoft Help Viewer 2.3                                               2.3.28307
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40664            12.0.40664.0   
Veeam Backup Transport                                                  12.1.0.2131
Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32532          14.36.32532
Microsoft Report Viewer 2012 Runtime                                    11.1.3452.0
Integration Services                                                    16.0.5395.0
Microsoft Active Directory Topology Diagrammer                          2.2.4146
Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664           12.0.40664
SSMS Post Install Tasks                                                 19.3.4.0
Microsoft Visual Studio Tools for Applications 2019 x86 Hosting Support 16.0.31110
SQL Server Management Studio Language Pack - English                    19.3.4.0
Microsoft Visual Studio Tools for Applications 2019                     16.0.31110
AD Replication Status Tool 1.0                                          3.22.415.100
RVTools                                                                 4.3.1
Administrative Templates (.admx) for Windows 10 October 2020 Update     1.0.0


PS C:\Users\jocolon>
```

**Comment by rebelinux** [comment] 2024-03-21 13:45
Fix will be included in next release v0.5.4.

**Comment by naval-sharma** [comment] 2024-03-21 13:53
You Rock mate! Thanks and keep doing good....

**Comment by naval-sharma** [comment] 2024-03-21 16:23
When can i expect the new version? Tried manipulating the existing code to no avail.

**Comment by rebelinux** [comment] 2024-03-21 16:49
You copy/paste the new code to the Get-AbrWinApplication.ps1 file?

if so, you need to import the module with the force option

`Import-Module AsBuiltReport.Microsoft.Windows -Force `

**Comment by naval-sharma** [comment] 2024-03-21 17:00
That worked! Stupid me, didnt realised Import-Module after amending code.

**Comment by naval-sharma** [comment] 2024-03-21 17:02
Another, offtopic, how to do a -Target $Server where $Server is Get-Content from a txt?

**Comment by rebelinux** [comment] 2024-03-21 18:36
Assuming the file is something like this :

[servers.txt](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Windows/files/14705603/servers.txt)

```powershell
$serverlist = get-content -Path .\servers.txt

# All server in single report file
New-AsBuiltReport -Report Microsoft.Windows -Target $serverlist  -OutputFolderPath C:\Users\username\ -Username domain\administrator -Password password -Format HTML,Word  -EnableHealthCheck

# One report file per server
foreach ($server in $serverlist) {
    New-AsBuiltReport -Report Microsoft.Windows -Target $server -OutputFolderPath C:\Users\userprofile -Username "domain\administrator" -Password 'password' -Format HTML,Word -EnableHealthCheck -Filename $server
}
```

**Closed as completed** 2024-04-08 12:34 UTC
Labels: bug
